export const WebhookTopics = {
  "APP_UNINSTALLED": "APP_UNINSTALLED",
  "CUSTOMERS_DATA_REQUEST": "CUSTOMERS_DATA_REQUEST",
  "CUSTOMERS_REDACT": "CUSTOMERS_REDACT",
  "SHOP_REDACT": "SHOP_REDACT",
}
